### Demo 1

np.array():生成向量或者矩阵

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [6]:
x.shape

(3,)

In [7]:
x.ndim

1

In [8]:
W = np.array([[1 ,2, 3], [4, 5, 6]])

In [9]:
W.shape

(2, 3)

In [10]:
W.ndim

2

矩阵对应元素的计算

In [11]:
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [12]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

广播：图形不一致的对应位置的乘积


In [13]:
A = np.array([[1, 2], [3, 4]])

In [14]:
A*10 # 【10】扩展成了数组A相同的情况，然后对应位相乘

array([[10, 20],
       [30, 40]])

In [15]:
b = np.array([10, 20]) # b被扩展成了与数组A相同的情况，然后对应位相乘
A*b

array([[10, 40],
       [30, 80]])

向量内积和矩阵乘积：np.dot()
> 当np.dot(x, y):
>   参数是一维数组：计算向量内积
>   参数是二维数组：计算矩阵乘积

In [16]:
# 向量内积
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [17]:
# 矩阵乘积
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

### Demo 02 神经网络复习

1. mini-batch版的全连接层变换
![神经网络](../imgs/chapter0102.png)

In [19]:
import numpy as np

In [21]:
W1 = np.random.randn(2,4)#权重
b1 = np.random.randn(4)#偏置
x = np.random.randn(10, 2)#输入
h = np.dot(x,W1)+b1 #b1的加法会触发广播功能

In [22]:
h

array([[-0.5689361 , -0.88580891, -0.0287992 , -2.62407764],
       [-0.94584889,  0.06583867, -0.95433171, -2.37918799],
       [ 0.19614424, -0.95234418,  0.22625103,  0.34726126],
       [ 0.92948246, -2.7489615 ,  1.97917332, -0.0270227 ],
       [-0.42708668, -0.55197511, -0.28285534, -1.42945001],
       [ 0.06870666,  0.16874077, -0.78249828,  1.91646224],
       [-1.49894605,  1.23463286, -2.11428782, -2.44323706],
       [-1.69169741,  1.29624695, -2.21758774, -3.10842007],
       [ 0.31199324, -1.33975787,  0.59334753,  0.0954945 ],
       [ 0.44648034, -1.78791668,  1.01812545, -0.19383336]])

> 全连接层的变换是**线性变换**，激活函数赋予它非线性的效果。
> 严格地讲，非线性地激活函数能增强神经网络的表现力

sigmoid激活函数的图像如下所示：
![sigmoid](../imgs/sigmoid.png)

In [23]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

a = sigmoid(h)

In [24]:
a

array([[0.36148235, 0.29197548, 0.4928007 , 0.06760481],
       [0.27972041, 0.51645373, 0.27801452, 0.08477355],
       [0.54887945, 0.27841363, 0.5563227 , 0.58595329],
       [0.71697028, 0.06014533, 0.87859301, 0.49324473],
       [0.39482222, 0.36540629, 0.42975389, 0.19318439],
       [0.51716991, 0.54208538, 0.3137817 , 0.87174341],
       [0.18258277, 0.7746284 , 0.10771586, 0.07993452],
       [0.15555275, 0.78520267, 0.09818218, 0.04276127],
       [0.57737171, 0.20754988, 0.64413285, 0.5238555 ],
       [0.60980208, 0.14332833, 0.7346073 , 0.45169281]])

### 完整版

In [1]:
import numpy as np
def sigmoid(x):
    return 1/(1+np.exp(-x))
x = np.random.randn(10,2)
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)

W2 = np.random.randn(4,3)
b2 = np.random.randn(3)

In [2]:
h = np.dot(x, W1)
a = sigmoid(h)
s = np.dot(a, W2)+b2

In [3]:
print(s) # 共10行，即10组数据；分成3类，取概率最大的那一类为结果

[[-0.77321166 -0.48782751  0.18067015]
 [-0.16356639 -0.41154684  0.52719573]
 [ 0.53837917 -0.0741918   0.88100971]
 [-0.22365587 -0.11713888  0.44473631]
 [ 0.24930179 -0.17704533  0.72228689]
 [-0.58580422 -0.78583765  0.3285916 ]
 [ 0.24270236 -0.56642706  0.79033225]
 [-0.55848233 -0.58867341  0.3248422 ]
 [ 0.21584459 -0.21025896  0.7081437 ]
 [-0.46901175 -0.37693344  0.34936595]]
